{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-config-generator.fullname" . }}
  {{- if .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
  labels:
    {{- include "k8s-config-generator.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.secret.stringData }}
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- else if .Values.secret.data }}
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
{{- end }}

