{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-config-generator.serviceAccountName" . }}
  {{- if .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
  labels:
    {{- include "k8s-config-generator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

