apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-config-generator.fullname" . }}
  {{- if .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
  labels:
    {{- include "k8s-config-generator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-port
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-config-generator.selectorLabels" . | nindent 4 }}
    tier: webserver
    layer: node

